name: Test

on:
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.5.1

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test
